// Date: 25/04/2014 10:33:11 PM
// Template version 1.1
// Java generated by Techne
// Keep in mind that you still need to fill in some blanks
// - ZeuX






package net.minecraft.src;

public class ModelNew extends ModelBase
{
  //fields
    ModelRenderer body;
    ModelRenderer rightleg;
    ModelRenderer leftleg;
    ModelRenderer bodyfront;
    ModelRenderer bodyleft;
    ModelRenderer bodyright;
    ModelRenderer bodyback;
    ModelRenderer lfrontmain;
    ModelRenderer lbackmain;
    ModelRenderer loutmain;
    ModelRenderer linmain;
    ModelRenderer lkneefront;
    ModelRenderer lkneefronttop;
    ModelRenderer lkneefrontbottom;
    ModelRenderer lbuttcheek;
    ModelRenderer lout;
    ModelRenderer lout2;
    ModelRenderer rfrontmain;
    ModelRenderer rbackmain;
    ModelRenderer routmain;
    ModelRenderer rinmain;
    ModelRenderer rkneefront;
    ModelRenderer rkneefronttop;
    ModelRenderer rkneefrontbottom;
    ModelRenderer rbuttcheek;
    ModelRenderer rout;
    ModelRenderer rout2;
  
  public ModelNew()
  {
    textureWidth = 64;
    textureHeight = 32;
    
      body = new ModelRenderer(this, 16, 16);
      body.addBox(-4F, 0F, -2F, 8, 12, 4);
      body.setRotationPoint(0F, 0F, 0F);
      body.setTextureSize(64, 32);
      body.mirror = true;
      setRotation(body, 0F, 0F, 0F);
      rightleg = new ModelRenderer(this, 0, 16);
      rightleg.addBox(-2F, 0F, -2F, 4, 12, 4);
      rightleg.setRotationPoint(-2F, 12F, 0F);
      rightleg.setTextureSize(64, 32);
      rightleg.mirror = true;
      setRotation(rightleg, 0F, 0F, 0F);
      leftleg = new ModelRenderer(this, 0, 16);
      leftleg.addBox(-2F, 0F, -2F, 4, 12, 4);
      leftleg.setRotationPoint(2F, 12F, 0F);
      leftleg.setTextureSize(64, 32);
      leftleg.mirror = true;
      setRotation(leftleg, 0F, 0F, 0F);
      bodyfront = new ModelRenderer(this, 40, 29);
      bodyfront.addBox(-4F, 10F, -2.5F, 8, 2, 1);
      bodyfront.setRotationPoint(0F, 0F, 0F);
      bodyfront.setTextureSize(64, 32);
      bodyfront.mirror = true;
      setRotation(bodyfront, 0F, 0F, 0F);
      bodyleft = new ModelRenderer(this, 4, 4);
      bodyleft.addBox(3.5F, 10F, -2F, 1, 2, 4);
      bodyleft.setRotationPoint(0F, 0F, 0F);
      bodyleft.setTextureSize(64, 32);
      bodyleft.mirror = true;
      setRotation(bodyleft, 0F, 0F, 0F);
      bodyright = new ModelRenderer(this, 4, 4);
      bodyright.addBox(-4.5F, 10F, -2F, 1, 2, 4);
      bodyright.setRotationPoint(0F, 0F, 0F);
      bodyright.setTextureSize(64, 32);
      bodyright.mirror = true;
      setRotation(bodyright, 0F, 0F, 0F);
      bodyback = new ModelRenderer(this, 40, 25);
      bodyback.addBox(-4F, 10F, 2F, 8, 3, 1);
      bodyback.setRotationPoint(0F, 0F, 0F);
      bodyback.setTextureSize(64, 32);
      bodyback.mirror = true;
      setRotation(bodyback, 0F, 0F, 0F);
      lfrontmain = new ModelRenderer(this, 54, 0);
      lfrontmain.addBox(0F, 12F, -2.5F, 4, 11, 1);
      lfrontmain.setRotationPoint(0F, 0F, 0F);
      lfrontmain.setTextureSize(64, 32);
      lfrontmain.mirror = true;
      setRotation(lfrontmain, 0F, 0F, 0F);
      lbackmain = new ModelRenderer(this, 44, 0);
      lbackmain.addBox(0F, 12F, 1.5F, 4, 11, 1);
      lbackmain.setRotationPoint(0F, 0F, 0F);
      lbackmain.setTextureSize(64, 32);
      lbackmain.mirror = true;
      setRotation(lbackmain, 0F, 0F, 0F);
      loutmain = new ModelRenderer(this, 34, 0);
      loutmain.addBox(3.5F, 12F, -2F, 1, 11, 4);
      loutmain.setRotationPoint(0F, 0F, 0F);
      loutmain.setTextureSize(64, 32);
      loutmain.mirror = true;
      setRotation(loutmain, 0F, 0F, 0F);
      linmain = new ModelRenderer(this, 24, 0);
      linmain.addBox(-0.5F, 12F, -2F, 1, 11, 4);
      linmain.setRotationPoint(0F, 0F, 0F);
      linmain.setTextureSize(64, 32);
      linmain.mirror = true;
      setRotation(linmain, 0F, 0F, 0F);
      lkneefront = new ModelRenderer(this, 0, 10);
      lkneefront.addBox(0F, 16F, -3F, 4, 2, 1);
      lkneefront.setRotationPoint(0F, 0F, 0F);
      lkneefront.setTextureSize(64, 32);
      lkneefront.mirror = true;
      setRotation(lkneefront, 0F, 0F, 0F);
      lkneefronttop = new ModelRenderer(this, 58, 28);
      lkneefronttop.addBox(1F, 15F, -3F, 2, 1, 1);
      lkneefronttop.setRotationPoint(0F, 0F, 0F);
      lkneefronttop.setTextureSize(64, 32);
      lkneefronttop.mirror = true;
      setRotation(lkneefronttop, 0F, 0F, 0F);
      lkneefrontbottom = new ModelRenderer(this, 14, 4);
      lkneefrontbottom.addBox(0F, 17.5F, -4F, 4, 5, 1);
      lkneefrontbottom.setRotationPoint(0F, 0F, 0F);
      lkneefrontbottom.setTextureSize(64, 32);
      lkneefrontbottom.mirror = true;
      setRotation(lkneefrontbottom, 0.0698132F, 0F, 0F);
      lbuttcheek = new ModelRenderer(this, 14, 0);
      lbuttcheek.addBox(0F, 13F, 2F, 4, 2, 1);
      lbuttcheek.setRotationPoint(0F, 0F, 0F);
      lbuttcheek.setTextureSize(64, 32);
      lbuttcheek.mirror = true;
      setRotation(lbuttcheek, -0.0174533F, 0F, 0F);
      lout = new ModelRenderer(this, 0, 0);
      lout.addBox(4F, 12F, -1F, 1, 3, 2);
      lout.setRotationPoint(0F, 0F, 0F);
      lout.setTextureSize(64, 32);
      lout.mirror = true;
      setRotation(lout, 0F, 0F, 0F);
      lout2 = new ModelRenderer(this, 6, 0);
      lout2.addBox(4F, 15F, -1F, 1, 2, 1);
      lout2.setRotationPoint(0F, 0F, 0F);
      lout2.setTextureSize(64, 32);
      lout2.mirror = true;
      setRotation(lout2, 0F, 0F, 0F);
      rfrontmain = new ModelRenderer(this, 54, 12);
      rfrontmain.addBox(-4F, 12F, -2.5F, 4, 11, 1);
      rfrontmain.setRotationPoint(0F, 0F, 0F);
      rfrontmain.setTextureSize(64, 32);
      rfrontmain.mirror = true;
      setRotation(rfrontmain, 0F, 0F, 0F);
      rbackmain = new ModelRenderer(this, 44, 12);
      rbackmain.addBox(-4F, 12F, 1.5F, 4, 11, 1);
      rbackmain.setRotationPoint(0F, 0F, 0F);
      rbackmain.setTextureSize(64, 32);
      rbackmain.mirror = true;
      setRotation(rbackmain, 0F, 0F, 0F);
      routmain = new ModelRenderer(this, 34, 0);
      routmain.addBox(-4.5F, 12F, -2F, 1, 11, 4);
      routmain.setRotationPoint(0F, 0F, 0F);
      routmain.setTextureSize(64, 32);
      routmain.mirror = true;
      setRotation(routmain, 0F, 0F, 0F);
      rinmain = new ModelRenderer(this, 24, 0);
      rinmain.addBox(-0.5F, 12F, -2F, 1, 11, 4);
      rinmain.setRotationPoint(0F, 0F, 0F);
      rinmain.setTextureSize(64, 32);
      rinmain.mirror = true;
      setRotation(rinmain, 0F, 0F, 0F);
      rkneefront = new ModelRenderer(this, 0, 13);
      rkneefront.addBox(-4F, 16F, -3F, 4, 2, 1);
      rkneefront.setRotationPoint(0F, 0F, 0F);
      rkneefront.setTextureSize(64, 32);
      rkneefront.mirror = true;
      setRotation(rkneefront, 0F, 0F, 0F);
      rkneefronttop = new ModelRenderer(this, 58, 30);
      rkneefronttop.addBox(-3F, 15F, -3F, 2, 1, 1);
      rkneefronttop.setRotationPoint(0F, 0F, 0F);
      rkneefronttop.setTextureSize(64, 32);
      rkneefronttop.mirror = true;
      setRotation(rkneefronttop, 0F, 0F, 0F);
      rkneefrontbottom = new ModelRenderer(this, 14, 10);
      rkneefrontbottom.addBox(-4F, 17.5F, -4F, 4, 5, 1);
      rkneefrontbottom.setRotationPoint(0F, 0F, 0F);
      rkneefrontbottom.setTextureSize(64, 32);
      rkneefrontbottom.mirror = true;
      setRotation(rkneefrontbottom, 0.0698132F, 0F, 0F);
      rbuttcheek = new ModelRenderer(this, 14, 0);
      rbuttcheek.addBox(-4F, 13F, 2F, 4, 2, 1);
      rbuttcheek.setRotationPoint(0F, 0F, 0F);
      rbuttcheek.setTextureSize(64, 32);
      rbuttcheek.mirror = true;
      setRotation(rbuttcheek, -0.0174533F, 0F, 0F);
      rout = new ModelRenderer(this, 0, 0);
      rout.addBox(-5F, 12F, -1F, 1, 3, 2);
      rout.setRotationPoint(0F, 0F, 0F);
      rout.setTextureSize(64, 32);
      rout.mirror = true;
      setRotation(rout, 0F, 0F, 0F);
      rout2 = new ModelRenderer(this, 6, 0);
      rout2.addBox(-5F, 15F, -1F, 1, 2, 1);
      rout2.setRotationPoint(0F, 0F, 0F);
      rout2.setTextureSize(64, 32);
      rout2.mirror = true;
      setRotation(rout2, 0F, 0F, 0F);
  }
  
  public void render(Entity entity, float f, float f1, float f2, float f3, float f4, float f5)
  {
    super.render(entity, f, f1, f2, f3, f4, f5);
    setRotationAngles(f, f1, f2, f3, f4, f5);
    body.render(f5);
    rightleg.render(f5);
    leftleg.render(f5);
    bodyfront.render(f5);
    bodyleft.render(f5);
    bodyright.render(f5);
    bodyback.render(f5);
    lfrontmain.render(f5);
    lbackmain.render(f5);
    loutmain.render(f5);
    linmain.render(f5);
    lkneefront.render(f5);
    lkneefronttop.render(f5);
    lkneefrontbottom.render(f5);
    lbuttcheek.render(f5);
    lout.render(f5);
    lout2.render(f5);
    rfrontmain.render(f5);
    rbackmain.render(f5);
    routmain.render(f5);
    rinmain.render(f5);
    rkneefront.render(f5);
    rkneefronttop.render(f5);
    rkneefrontbottom.render(f5);
    rbuttcheek.render(f5);
    rout.render(f5);
    rout2.render(f5);
  }
  
  private void setRotation(ModelRenderer model, float x, float y, float z)
  {
    model.rotateAngleX = x;
    model.rotateAngleY = y;
    model.rotateAngleZ = z;
  }
  
  public void setRotationAngles(float f, float f1, float f2, float f3, float f4, float f5)
  {
    super.setRotationAngles(f, f1, f2, f3, f4, f5);
  }

}
