// Date: 12/04/2014 5:28:16 PM
// Template version 1.1
// Java generated by Techne
// - ZeuX

package me.toofifty.ironsuits.model;

import net.minecraft.client.model.ModelBiped;
import net.minecraft.client.model.ModelRenderer;
import net.minecraft.entity.Entity;

public class ModelExoHelmet extends ModelArmorBase {
	// fields
	ModelRenderer hrightside;
	ModelRenderer hfrontforehead;
	ModelRenderer hfrontbottom;
	ModelRenderer hfrontmiddle;
	ModelRenderer htop;
	ModelRenderer hleftside;
	ModelRenderer hback;
	ModelRenderer hbackbottom;
	ModelRenderer htop2;
	ModelRenderer htop1;
	ModelRenderer htop3;

	public ModelExoHelmet(float f) {
		super(f);

		textureWidth = 64;
		textureHeight = 32;

		hrightside = new ModelRenderer(this, 46, 22);
		hrightside.addBox(4F, -2F, -4F, 1, 2, 8);
		hrightside.setRotationPoint(0F, 0F, 0F);
		hrightside.setTextureSize(64, 32);
		hrightside.mirror = true;
		setRotation(hrightside, 0F, 0F, 0F);
		hfrontforehead = new ModelRenderer(this, 13, 23);
		hfrontforehead.addBox(-1F, -9F, -5F, 2, 6, 1);
		hfrontforehead.setRotationPoint(0F, 0F, 0F);
		hfrontforehead.setTextureSize(64, 32);
		hfrontforehead.mirror = true;
		setRotation(hfrontforehead, 0F, 0F, 0F);
		hfrontbottom = new ModelRenderer(this, 20, 26);
		hfrontbottom.addBox(-5F, -2F, -5F, 10, 2, 1);
		hfrontbottom.setRotationPoint(0F, 0F, 0F);
		hfrontbottom.setTextureSize(64, 32);
		hfrontbottom.mirror = true;
		setRotation(hfrontbottom, 0F, 0F, 0F);
		hfrontmiddle = new ModelRenderer(this, 0, 18);
		hfrontmiddle.addBox(-2F, -3F, -6F, 4, 3, 2);
		hfrontmiddle.setRotationPoint(0F, 0F, 0F);
		hfrontmiddle.setTextureSize(64, 32);
		hfrontmiddle.mirror = true;
		setRotation(hfrontmiddle, 0F, 0F, 0F);
		htop = new ModelRenderer(this, 0, 23);
		htop.addBox(-1F, -9F, -4F, 2, 1, 8);
		htop.setRotationPoint(0F, 0F, 0F);
		htop.setTextureSize(64, 32);
		htop.mirror = true;
		setRotation(htop, 0F, 0F, 0F);
		hleftside = new ModelRenderer(this, 46, 22);
		hleftside.addBox(-5F, -2F, -4F, 1, 2, 8);
		hleftside.setRotationPoint(0F, 0F, 0F);
		hleftside.setTextureSize(64, 32);
		hleftside.mirror = true;
		setRotation(hleftside, 0F, 0F, 0F);
		hback = new ModelRenderer(this, 1, 23);
		hback.addBox(-1F, -9F, 4F, 2, 7, 1);
		hback.setRotationPoint(0F, 0F, 0F);
		hback.setTextureSize(64, 32);
		hback.mirror = true;
		setRotation(hback, 0F, 0F, 0F);
		hbackbottom = new ModelRenderer(this, 20, 29);
		hbackbottom.addBox(-5F, -2F, 4F, 10, 2, 1);
		hbackbottom.setRotationPoint(0F, 0F, 0F);
		hbackbottom.setTextureSize(64, 32);
		hbackbottom.mirror = true;
		setRotation(hbackbottom, 0F, 0F, 0F);
		htop2 = new ModelRenderer(this, 10, 16);
		htop2.addBox(-2F, -9F, 2F, 4, 1, 1);
		htop2.setRotationPoint(0F, 0F, 0F);
		htop2.setTextureSize(64, 32);
		htop2.mirror = true;
		setRotation(htop2, 0F, 0F, 0F);
		htop1 = new ModelRenderer(this, 0, 16);
		htop1.addBox(-2F, -9F, -2F, 4, 1, 1);
		htop1.setRotationPoint(0F, 0F, 0F);
		htop1.setTextureSize(64, 32);
		htop1.mirror = true;
		setRotation(htop1, 0F, 0F, 0F);
		htop3 = new ModelRenderer(this, 20, 16);
		htop3.addBox(-2F, -9F, 0F, 4, 1, 1);
		htop3.setRotationPoint(0F, 0F, 0F);
		htop3.setTextureSize(64, 32);
		htop3.mirror = true;
		setRotation(htop3, 0F, 0F, 0F);

		this.bipedHead.addChild(hrightside);
		this.bipedHead.addChild(hfrontforehead);
		this.bipedHead.addChild(hfrontbottom);
		this.bipedHead.addChild(hfrontmiddle);
		this.bipedHead.addChild(htop);
		this.bipedHead.addChild(hleftside);
		this.bipedHead.addChild(hback);
		this.bipedHead.addChild(hbackbottom);
		this.bipedHead.addChild(htop1);
		this.bipedHead.addChild(htop2);
		this.bipedHead.addChild(htop3);
	}

	@Override
	public void render(Entity entity, float f, float f1, float f2, float f3,
			float f4, float f5) {
		super.render(entity, f, f1, f2, f3, f4, f5);
		setRotationAngles(f, f1, f2, f3, f4, f5, entity);
	}

	public void defaultRender(float f) {
		this.hrightside.render(f);
		this.hfrontforehead.render(f);
		this.hfrontbottom.render(f);
		this.hfrontmiddle.render(f);
		this.htop.render(f);
		this.hleftside.render(f);
		this.hback.render(f);
		this.hbackbottom.render(f);
		this.htop1.render(f);
		this.htop2.render(f);
		this.htop3.render(f);
	}

	public void renderInventory(float f) {
		this.hrightside.render(f);
		this.hfrontforehead.render(f);
		this.hfrontbottom.render(f);
		this.hfrontmiddle.render(f);
		this.htop.render(f);
		this.hleftside.render(f);
		this.hback.render(f);
		this.hbackbottom.render(f);
		this.htop1.render(f);
		this.htop2.render(f);
		this.htop3.render(f);
	}

	private void setRotation(ModelRenderer model, float x, float y, float z) {
		model.rotateAngleX = x;
		model.rotateAngleY = y;
		model.rotateAngleZ = z;
	}
}
